<?php

namespace FoodBundle\Repository;

use Doctrine\ORM\EntityRepository;
use FoodBundle\Entity\User;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends EntityRepository
{
    public function findFilteredOrderedByUserId(User $user)
    {
        $em = $this->getEntityManager();
        $gb = $em->createQueryBuilder()
            ->select('t')
            ->from('FoodBundle:Transaction', 't')
            ->innerJoin('t.user', 'u')
            ->where('u.id = :user')
//            ->innerJoin('t.user', 'u')
//            ->where('u.id = :user')
            ->setParameter('user', $user->getId());
//            ->where('p.portions > 0 and p.expiration> :time')
//            ->orderBy($order, $direction)
//            ->setParameter('time', date('Y-m-d H:i:s'));

        $query = $gb->getQuery();
        return $query->getResult();

    }

    public function findFilteredOrderedByPostUserId(User $user)
    {
        $em = $this->getEntityManager();
        $gb = $em->createQueryBuilder()
            ->select('t')
            ->from('FoodBundle:Transaction', 't')
            ->innerJoin('t.posts', 'p')
            ->innerJoin('p.user', 'u')
            ->where('u.id = :user')
//            ->innerJoin('t.user', 'u')
//            ->where('u.id = :user')
            ->setParameter('user', $user->getId());
//            ->where('p.portions > 0 and p.expiration> :time')
//            ->orderBy($order, $direction)
//            ->setParameter('time', date('Y-m-d H:i:s'));

        $query = $gb->getQuery();
        return $query->getResult();

    }
}
